"""
Popula o banco instance/prj.db com os dados que estavam hardcoded no dashboard.
Execute uma única vez: python seed.py
"""
from database import init_db, insert_imovel

INITIAL_DATA = [
    {"mat_tipo":"8112",       "tipologia":"Galpão",           "cidade":"Santos",                 "estado":"SP","tipo_imovel":"Urbano","vm_enforce":21201520,"vf_enforce":15901140,"area_terreno":42000,    "unid_area_terreno":"m²","status":"Não Vendido",  "obs":"-",                                                                   "tabela_gi":"25000000","proposta":None,     "lat":-23.9618,"lng":-46.3322},
    {"mat_tipo":"1756",       "tipologia":"Agroindustria",    "cidade":"Assis Chateaubriand",    "estado":"PR","tipo_imovel":"Rural", "vm_enforce":15039375,"vf_enforce":13197052,"area_terreno":13587.75, "unid_area_terreno":"ha", "status":"Vendido",      "obs":"Vendido — Indenização (MATS 1.756, 1.757, 1.758 E 1.759)",            "tabela_gi":None,      "proposta":3000000,  "previsao_registro":"12/01/2026","lat":-24.4167,"lng":-53.5167},
    {"mat_tipo":"25510",      "tipologia":"Agroindustria",    "cidade":"Dourados",               "estado":"MS","tipo_imovel":"Rural", "vm_enforce":13155059,"vf_enforce":11395570,"area_terreno":7.26,     "unid_area_terreno":"ha", "status":"Não Vendido",  "obs":"Em aprovação (comitê)",                                                "tabela_gi":None,      "proposta":13000000, "previsao_registro":"26/03/2026","lat":-22.2212,"lng":-54.8055},
    {"mat_tipo":"58840",      "tipologia":"Prédio Comercial", "cidade":"Vargem Grande Paulista", "estado":"SP","tipo_imovel":"Urbano","vm_enforce":13145579,"vf_enforce":10516463,"area_terreno":1407,     "unid_area_terreno":"m²","status":"Proposta em Negociação","obs":"Proposta distante",                                           "tabela_gi":"45000000","proposta":6000000,  "previsao_registro":"01/07/2026","lat":-23.6019,"lng":-47.0300},
    {"mat_tipo":"23697",      "tipologia":"Agroindustria",    "cidade":"—",                      "estado":"PR","tipo_imovel":"Rural", "vm_enforce":14301000,"vf_enforce":9790000, "area_terreno":None,     "unid_area_terreno":None, "status":"Vendido",      "obs":"Vendido (Integrada)",                                                  "tabela_gi":None,      "proposta":26000000, "comprador":"Cooperativa INTEGRADA","lat":-23.4208,"lng":-51.9331},
    {"mat_tipo":"39606",      "tipologia":"Prédio Comercial", "cidade":"Jacareí",                "estado":"SP","tipo_imovel":"Urbano","vm_enforce":8836364, "vf_enforce":7883985, "area_terreno":3250,     "unid_area_terreno":"m²","status":"Proposta em Negociação","obs":"Proposta em negociação - tabela de GI",                       "tabela_gi":"22500000","proposta":13000000, "comprador":"Empresário da cidade","lat":-23.2947,"lng":-45.9653},
    {"mat_tipo":"2164",       "tipologia":"Gleba",            "cidade":"Taciba",                 "estado":"SP","tipo_imovel":"Rural", "vm_enforce":8775718, "vf_enforce":7140620, "area_terreno":176.35,   "unid_area_terreno":"ha", "status":"Não Vendido",  "obs":"Arrendatário plantou eucalipto",                                       "tabela_gi":None,      "proposta":None,     "lat":-22.3953,"lng":-51.2800},
    {"mat_tipo":"26999",      "tipologia":"Prédio Comercial", "cidade":"Bragança Paulista",      "estado":"SP","tipo_imovel":"Urbano","vm_enforce":6484813, "vf_enforce":6484813, "area_terreno":4036.77,  "unid_area_terreno":"m²","status":"Proposta em Negociação","obs":"Proposta em negociação - tabela de GI",                       "tabela_gi":"13000000","proposta":10000000, "lat":-22.9516,"lng":-46.5416},
    {"mat_tipo":"10565",      "tipologia":"Agroindustria",    "cidade":"Fátima do Sul",          "estado":"MS","tipo_imovel":"Rural", "vm_enforce":6971320, "vf_enforce":5594484, "area_terreno":13.43,    "unid_area_terreno":"ha", "status":"Não Vendido",  "obs":"Sem proposta",                                                         "tabela_gi":None,      "proposta":None,     "lat":-22.5107,"lng":-54.0507},
    {"mat_tipo":"145993",     "tipologia":"Gleba",            "cidade":"Dourados",               "estado":"MS","tipo_imovel":"Rural", "vm_enforce":6108735, "vf_enforce":4956143, "area_terreno":87.83,    "unid_area_terreno":"ha", "status":"Não Vendido",  "obs":"Negociação em andamento",                                              "tabela_gi":None,      "proposta":None,     "previsao_registro":"25/05/2026","lat":-22.2512,"lng":-54.7755},
    {"mat_tipo":"6896",       "tipologia":"Terreno",          "cidade":"Maringá",                "estado":"PR","tipo_imovel":"Urbano","vm_enforce":6875426, "vf_enforce":4881552, "area_terreno":15000,    "unid_area_terreno":"m²","status":"Vendido",      "obs":"Vendido",                                                              "tabela_gi":"18000000","proposta":18000000, "comprador":"MC Incorporações","previsao_registro":"01/07/2026","lat":-23.4205,"lng":-51.9333},
    {"mat_tipo":"1615",       "tipologia":"Agroindustria",    "cidade":"Canoinhas",              "estado":"SC","tipo_imovel":"Rural", "vm_enforce":5570395, "vf_enforce":4741799, "area_terreno":32920,    "unid_area_terreno":"ha", "status":"Vendido",      "obs":"Vendido (Cooperativa Agricola de Canoinhas)",                          "tabela_gi":None,      "proposta":7000000,  "comprador":"Cooperativa Agricola de Canoinhas","previsao_registro":"13/04/2026","lat":-26.1786,"lng":-50.3917},
    {"mat_tipo":"146005",     "tipologia":"Gleba",            "cidade":"Dourados",               "estado":"MS","tipo_imovel":"Rural", "vm_enforce":5325769, "vf_enforce":4320907, "area_terreno":86.67,    "unid_area_terreno":"ha", "status":"Não Vendido",  "obs":"Negociação em andamento",                                              "tabela_gi":None,      "proposta":None,     "previsao_registro":"25/05/2026","lat":-22.2012,"lng":-54.8355},
    {"mat_tipo":"4479",       "tipologia":"Agroindustria",    "cidade":"Mauá da Serra",          "estado":"PR","tipo_imovel":"Rural", "vm_enforce":4986949, "vf_enforce":4319945, "area_terreno":27104,    "unid_area_terreno":"ha", "status":"Vendido",      "obs":"Vendido (Integrada)",                                                  "tabela_gi":None,      "proposta":None,     "comprador":"Cooperativa INTEGRADA","lat":-23.9000,"lng":-51.2500},
    {"mat_tipo":"9846",       "tipologia":"Agroindustria",    "cidade":"Floraí",                 "estado":"PR","tipo_imovel":"Rural", "vm_enforce":4279250, "vf_enforce":3803183, "area_terreno":17430,    "unid_area_terreno":"ha", "status":"Vendido",      "obs":"Vendido (Integrada)",                                                  "tabela_gi":None,      "proposta":None,     "comprador":"Cooperativa INTEGRADA","previsao_registro":"02/10/2026","lat":-23.3156,"lng":-52.2744},
    {"mat_tipo":"5377",       "tipologia":"Agroindustria",    "cidade":"Rancho Alegre",          "estado":"PR","tipo_imovel":"Rural", "vm_enforce":3376178, "vf_enforce":3000578, "area_terreno":76230,    "unid_area_terreno":"ha", "status":"Vendido",      "obs":"Vendido (Integrada)",                                                  "tabela_gi":None,      "proposta":None,     "comprador":"Cooperativa INTEGRADA","previsao_registro":"02/10/2026","lat":-23.5978,"lng":-51.0028},
    {"mat_tipo":"35948",      "tipologia":"Prédio Comercial", "cidade":"Indaiatuba",             "estado":"SP","tipo_imovel":"Urbano","vm_enforce":3076885, "vf_enforce":2615352, "area_terreno":2442,     "unid_area_terreno":"m²","status":"Proposta em Negociação","obs":"Proposta em negociação - tabela de GI",                       "tabela_gi":"5200000", "proposta":3500000,  "comprador":"Investidor e Incorporadora","previsao_registro":"26/03/2026","lat":-23.0900,"lng":-47.2197},
    {"mat_tipo":"360",        "tipologia":"Barracão",         "cidade":"Piedade",                "estado":"SP","tipo_imovel":"Urbano","vm_enforce":2199235, "vf_enforce":2199235, "area_terreno":3800,     "unid_area_terreno":"m²","status":"Não Vendido",  "obs":"-",                                                                   "tabela_gi":"NÃO LIBERADO","proposta":None, "previsao_registro":"26/03/2026","lat":-23.9119,"lng":-47.4267},
    {"mat_tipo":"2464",       "tipologia":"Gleba",            "cidade":"Assaí",                  "estado":"PR","tipo_imovel":"Rural", "vm_enforce":2572652, "vf_enforce":2064553, "area_terreno":591690,   "unid_area_terreno":"ha", "status":"Não Vendido",  "obs":"Negociação em andamento",                                              "tabela_gi":None,      "proposta":None,     "previsao_registro":"26/04/2026","lat":-23.3694,"lng":-50.8531},
    {"mat_tipo":"6193",       "tipologia":"Agroindustria",    "cidade":"Mauá da Serra",          "estado":"PR","tipo_imovel":"Rural", "vm_enforce":1893464, "vf_enforce":1640213, "area_terreno":20000,    "unid_area_terreno":"ha", "status":"Vendido",      "obs":"Vendido (Integrada)",                                                  "tabela_gi":None,      "proposta":None,     "comprador":"Cooperativa INTEGRADA","lat":-23.9200,"lng":-51.2300},
    {"mat_tipo":"25766",      "tipologia":"Galpão",           "cidade":"Itapeva",                "estado":"SP","tipo_imovel":"Urbano","vm_enforce":1537000, "vf_enforce":1537000, "area_terreno":None,     "unid_area_terreno":None, "status":"Proposta em Negociação","obs":"Proposta em negociação - tabela de GI",                       "tabela_gi":"2500000", "proposta":2200000,  "comprador":"Investidor local e comodatário","previsao_registro":"06/03/2026","lat":-23.9822,"lng":-48.8757},
    {"mat_tipo":"2053",       "tipologia":"Galpão Industrial","cidade":"Curitibanos",            "estado":"SC","tipo_imovel":"Urbano","vm_enforce":1411200, "vf_enforce":1411200, "area_terreno":10000,    "unid_area_terreno":"m²","status":"Não Vendido",  "obs":"Proposta em negociação - tabela de GI",                               "tabela_gi":"10500000","proposta":4000000,  "previsao_registro":"AGUARDANDO DEFINIÇÃO QUANTO AO PAGAMENTO DAS DÍVIDAS DA CAC","lat":-27.2825,"lng":-50.5783},
    {"mat_tipo":"11142",      "tipologia":"Terreno",          "cidade":"Piedade",                "estado":"SP","tipo_imovel":"Urbano","vm_enforce":1517475, "vf_enforce":1138106, "area_terreno":1048,     "unid_area_terreno":"m²","status":"Não Vendido",  "obs":"-",                                                                   "tabela_gi":"NÃO LIBERADO","proposta":None, "previsao_registro":"19/06/2026","lat":-23.9319,"lng":-47.4467},
    {"mat_tipo":"4379",       "tipologia":"Galpão",           "cidade":"Santo Anastácio",        "estado":"SP","tipo_imovel":"Urbano","vm_enforce":1013342, "vf_enforce":709340,  "area_terreno":3371.4,   "unid_area_terreno":"m²","status":"Não Vendido",  "obs":"-",                                                                   "tabela_gi":"1600000", "proposta":None,     "lat":-21.9758,"lng":-51.6564},
    {"mat_tipo":"579",        "tipologia":"Galpão",           "cidade":"Estrela do Sul",         "estado":"MG","tipo_imovel":"Rural", "vm_enforce":527500,  "vf_enforce":456947,  "area_terreno":5.1,      "unid_area_terreno":"ha", "status":"Vendido",      "obs":"Vendido",                                                              "tabela_gi":None,      "proposta":900000,   "comprador":"Eucamed","lat":-18.7378,"lng":-47.6903},
    {"mat_tipo":"1453",       "tipologia":"Galpão",           "cidade":"São Joaquim",            "estado":"SC","tipo_imovel":"Urbano","vm_enforce":2558432, "vf_enforce":430072,  "area_terreno":None,     "unid_area_terreno":"ha", "status":"Proposta em Negociação","obs":"Proposta em negociação - tabela de GI",                       "tabela_gi":"12000000","proposta":8000000,  "comprador":"Cooperativa INTEGRADA","lat":-28.2943,"lng":-49.9308},
    {"mat_tipo":"2629",       "tipologia":"Terreno",          "cidade":"Assaí",                  "estado":"PR","tipo_imovel":"Urbano","vm_enforce":548855,  "vf_enforce":411641,  "area_terreno":3717,     "unid_area_terreno":"m²","status":"Não Vendido",  "obs":"-",                                                                   "tabela_gi":"NÃO LIBERADO","proposta":None, "previsao_registro":"26/04/2026","lat":-23.3794,"lng":-50.8631},
    {"mat_tipo":"3495",       "tipologia":"Fazenda",          "cidade":"Tiros",                  "estado":"MG","tipo_imovel":"Rural", "vm_enforce":332540,  "vf_enforce":332540,  "area_terreno":687.75,   "unid_area_terreno":"ha", "status":"Não Vendido",  "obs":"Sem proposta",                                                         "tabela_gi":None,      "proposta":None,     "previsao_registro":"26/03/2026","lat":-18.9800,"lng":-45.9667},
    {"mat_tipo":"7632",       "tipologia":"Gleba",            "cidade":"Assaí",                  "estado":"PR","tipo_imovel":"Urbano","vm_enforce":316814,  "vf_enforce":316814,  "area_terreno":115610,   "unid_area_terreno":"m²","status":"Não Vendido",  "obs":"-",                                                                   "tabela_gi":"NÃO LIBERADO","proposta":None, "previsao_registro":"25/05/2026","lat":-23.3894,"lng":-50.8731},
    {"mat_tipo":"8701",       "tipologia":"Gleba",            "cidade":"Guaíra",                 "estado":"PR","tipo_imovel":"Rural", "vm_enforce":391730,  "vf_enforce":314585,  "area_terreno":55.66,    "unid_area_terreno":"ha", "status":"Não Vendido",  "obs":"Aguardando formalização",                                              "tabela_gi":None,      "proposta":350000,   "previsao_registro":"19/03/2026","lat":-24.0769,"lng":-54.2561},
    {"mat_tipo":"3222",       "tipologia":"Chácara Urbana",   "cidade":"Assaí",                  "estado":"PR","tipo_imovel":"Urbano","vm_enforce":404291,  "vf_enforce":303218,  "area_terreno":7006,     "unid_area_terreno":"ha", "status":"Não Vendido",  "obs":"Proposta em negociação - tabela de GI",                               "tabela_gi":"1980000", "proposta":1500000,  "previsao_registro":"26/04/2026","lat":-23.3594,"lng":-50.8431},
    {"mat_tipo":"7047",       "tipologia":"Casa Residencial", "cidade":"Tatuí",                  "estado":"SP","tipo_imovel":"Urbano","vm_enforce":283290,  "vf_enforce":198303,  "area_terreno":250,      "unid_area_terreno":"m²","status":"Não Vendido",  "obs":"-",                                                                   "tabela_gi":"NÃO LIBERADO","proposta":None, "lat":-23.3561,"lng":-47.8575},
    {"mat_tipo":"51",         "tipologia":"Chácara Urbana",   "cidade":"São Roque",              "estado":"SP","tipo_imovel":"Urbano","vm_enforce":164136,  "vf_enforce":164136,  "area_terreno":580800,   "unid_area_terreno":"m²","status":"Não Vendido",  "obs":"-",                                                                   "tabela_gi":"NÃO LIBERADO","proposta":None, "previsao_registro":"26/06/2026","lat":-23.5295,"lng":-47.1371},
    {"mat_tipo":"147628",     "tipologia":"Apartamento",      "cidade":"Rio de Janeiro",         "estado":"RJ","tipo_imovel":"Urbano","vm_enforce":173345,  "vf_enforce":86673,   "area_terreno":None,     "unid_area_terreno":"m²","status":"Não Vendido",  "obs":"-",                                                                   "tabela_gi":"NÃO LIBERADO","proposta":None, "previsao_registro":"13/04/2026","lat":-22.9068,"lng":-43.1729},
    {"mat_tipo":"11444",      "tipologia":"Prédio Comercial", "cidade":"Guarapuava",             "estado":"PR","tipo_imovel":"Urbano","vm_enforce":86187,   "vf_enforce":86187,   "area_terreno":698.75,   "unid_area_terreno":"m²","status":"Não Vendido",  "obs":"-",                                                                   "tabela_gi":"NÃO LIBERADO","proposta":None, "previsao_registro":"19/03/2026","lat":-25.3896,"lng":-51.4625},
    {"mat_tipo":"15927",      "tipologia":"Chácara Urbana",   "cidade":"São Roque",              "estado":"SP","tipo_imovel":"Urbano","vm_enforce":0,       "vf_enforce":0,       "area_terreno":12000,    "unid_area_terreno":"m²","status":"Não Vendido",  "obs":"-",                                                                   "tabela_gi":None,      "proposta":None,     "previsao_registro":"26/06/2026","lat":-23.5395,"lng":-47.1471},
    {"mat_tipo":"Posse",      "tipologia":"—",                "cidade":"—",                      "estado":"SP","tipo_imovel":"Urbano","vm_enforce":0,       "vf_enforce":0,       "area_terreno":None,     "unid_area_terreno":None, "status":"Não Vendido",  "obs":"-",                                                                   "tabela_gi":None,      "proposta":None,     "lat":None,"lng":None},
    {"mat_tipo":"Equipamentos","tipologia":"—",               "cidade":"—",                      "estado":"GO","tipo_imovel":"Rural", "vm_enforce":0,       "vf_enforce":3900000, "area_terreno":None,     "unid_area_terreno":None, "status":"Não Vendido",  "obs":"Negociação em andamento",                                              "tabela_gi":"2500000", "proposta":2200000,  "comprador":"Investidor local e comodatário","previsao_registro":"06/03/2026","lat":-16.6869,"lng":-49.2648},
]

if __name__ == "__main__":
    init_db()
    count = 0
    for row in INITIAL_DATA:
        insert_imovel(row)
        count += 1
    print(f"{count} imóveis inseridos em instance/prj.db")
